#!/bin/bash

gnulib-tool --source-base=gnulib \
	    --m4-base=gnulib/m4 \
	    --aux-dir=gnulib/build-aux \
	    --import \
	    argp \
	    calloc-gnu \
	    dprintf-posix \
	    dirname \
	    environ \
	    error \
	    fnmatch-gnu \
	    fprintf-posix \
	    fopen-gnu \
	    getline \
	    getopt-gnu \
	    getpass-gnu \
	    glob \
	    ioctl \
	    malloc-gnu \
	    mbsrtowcs \
	    nonblocking \
	    obstack-printf-posix \
	    pipe-posix \
	    printf-posix \
	    progname \
	    realloc-gnu \
	    select \
	    setenv \
	    sigpipe \
	    snprintf-posix \
	    sprintf-posix \
	    stdio \
	    stdlib \
	    strcase \
	    strcasestr \
	    strdup-posix \
	    strerror_r-posix \
	    sys_ioctl \
	    system-posix \
	    termios \
	    unistd \
	    vasnprintf-posix \
	    vasprintf-posix \
	    vdprintf-posix \
	    vfprintf-posix \
	    vprintf-posix \
	    vsnprintf-posix \
	    vsprintf-posix \
	    wcslen \
	    wcsncpy \
	    wcsrtombs \
	    wmemcpy \
	    xprintf-posix \
	    xvasprintf-posix \
	    xalloc

mv build-aux/texinfo.tex{,.bkp}
autoreconf --install --force
mv build-aux/texinfo.tex{.bkp,}
