\input texinfo  @c -*-texinfo-*-
@c
@c mininim.texi -- The MININIM Manual
@c
@c Copyright (C) 2016 Bruno Félix Rezende Ribeiro <oitofelix@gnu.org>
@c
@c Permission is granted to copy, distribute and/or modify this
@c document under the terms of the GNU Free Documentation License,
@c Version 1.3 or any later version published by the Free Software
@c Foundation; with no Invariant Sections.
@c
@c You should have received a copy of the GNU Free Documentation
@c License along with this program.  If not, see
@c <http://www.gnu.org/licenses/>.
@c

@c %**start of header
@setfilename mininim.info
@documentencoding UTF-8
@c @documentlanguage en_US
@firstparagraphindent insert
@footnotestyle end
@include release.texi
@settitle MININIM
@set manual
@set GNUphiThird
@c %**end of header





@c --- Macros;
@c @macro webdoc{text, url}
@c @inlinefmtifelse{info, @emph{\text\}@footnote{See @url{\url\}.},
@c @inlinefmtifelse{html, @url{\url\,,\text\},
@c @inlinefmtifelse{tex, @url{\url\,,@emph{\text\}}@footnote{See @url{\url\}.},
@c @url{\url\,,@emph{\text\}}@footnote{See @url{\url\}.}}}}
@c @end macro

@c @macro n
@c @inlinefmt{tex,}
@c @end macro




@include copying.texi





@c --- Info directory entry;
@dircategory Games
@direntry
* MININIM: (mininim).   The Advanced Prince of Persia Engine.
@end direntry





@c --- Info Top Node;
@ifnottex
@node Top
@top MININIM: The Advanced Prince of Persia Engine
@insertcopying
@end ifnottex





@c --- Menu;
@menu
* Constructions:: The matter the world is made of
* Movements:: How the kid reacts to user input



@c * Preface::    Motivation, program definition and document organization;

@c * Overview::   Description, distribution, obtaining, contact, bug reports,
@c                 contribution, donation and hacking;
@c * Release::    Information specifically relevant for the current release;

@c Appendices:
@c * GNU Free Documentation License:: The license for this documentation;

@c GNU philosophy:
@c * The GNU Manifesto::
@c * The GNU Project::
@c * Linux and the GNU system::
@c * Why Software Should Not Have Owners::
@c * Why Free Software Needs Free Documentation::

Indexes:
* Index:: Concepts and reference material.
@end menu





@c --- Title page;
@finalout
@titlepage
@title @value{package} @value{version}
@subtitle The Advanced Prince of Persia Engine (a childhood dream)
@sp 6
@center @image{mininim-figures/mininim,2in}
@author Bruno Félix Rezende Ribeiro <@email{oitofelix@@gnu.org}>
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage





@c --- Table of contents;
@contents





@c --- Constructions;
@node Constructions
@chapter Constructions
@cindex constructions

Each @dfn{level} is comprised of @dfn{rooms}@footnote{The terminology
used for @dfn{rooms} in the original game is @dfn{screens}.}.  Each room
is a comprised of three @dfn{floors}.  Each floor is comprised of 10
@dfn{places}.  Each place holds a @dfn{construction} (or @dfn{con} for
short) @footnote{The terminology used for @dfn{constructions} in the
original game is @dfn{tiles}.}.

@center @image{mininim-figures/level-layout}

@section Foregrounds

All traversable, collidable, rigid and trap constructions are marked as
such.  Non-hangable conditions are noted as well.

Explain design field.

@subsection Floors

All depressible floors are marked as such.

@multitable @columnfractions .25 .15 .15 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{NO_FLOOR}
  @tab
  @tab
  @tab For the dungeon and palace this results in no graphics at all.
  This is an @emph{strictly traversable construction}.

  @item @code{FLOOR}
  @tab @center @image{mininim-figures/d-floor}
  @tab @center @image{mininim-figures/p-floor}
  @tab This is a normal floor.

  @item @code{BROKEN_FLOOR}
  @tab @center @image{mininim-figures/d-broken-floor}
  @tab @center @image{mininim-figures/p-broken-floor}
  @tab This behaves like @code{FLOOR}.  As soon as a falling
  @code{LOOSE_FLOOR} encounters a rigid construction, it creates a
  @code{BROKEN_FLOOR} over it.

  @item @code{SKELETON_FLOOR}
  @tab @center @image{mininim-figures/d-skeleton-floor}
  @tab @center @image{mininim-figures/p-skeleton-floor}
  @footnote{The original game has no palace version of the skeleton floor.}
  @tab This behaves like @code{FLOOR}.

  @item @code{LOOSE_FLOOR}
  @tab @center @image{mininim-figures/d-loose-floor}
  @tab @center @image{mininim-figures/p-loose-floor}
  @tab This is rendered as @code{FLOOR}, but shakes as the kid hits the
  ground.  If the kid is near enough it's released and falls.  This is a
  @emph{traversable construction}. This is a @emph{depressible floor}.
  This is a @emph{trap construction}.

  @item @code{SPIKES_FLOOR}
  @tab @center @image{mininim-figures/d-spikes-floor}
  @tab @center @image{mininim-figures/p-spikes-floor}
  @tab Spikes come out of it, killing the kid if he falls or step too
  fast over it.  This is a @emph{trap construction}.

  @item @code{OPENER_FLOOR}
  @tab @center @image{mininim-figures/d-opener-floor}
  @tab @center @image{mininim-figures/p-opener-floor}
  @tab This opens one or more doors.  This is a @emph{depressible floor}.

  @item @code{CLOSER_FLOOR}
  @tab @center @image{mininim-figures/d-closer-floor}
  @tab @center @image{mininim-figures/p-closer-floor}
  @tab  This closes one or more doors. This is a @emph{depressible floor}.

  @item @code{STUCK_FLOOR}
  @tab @center @image{mininim-figures/d-stuck-floor}
  @tab @center @image{mininim-figures/p-stuck-floor}
  @tab This is rendered like a pressed @code{CLOSER_FLOOR}, but it can't
  be unpressed.

  @item @code{HIDDEN_FLOOR}
  @tab
  @tab
  @tab This is rendered as @code{NO_FLOOR}, but as soon as the kid
  presses it, it's replaced by @code{FLOOR}.  This is a
  @emph{depressible floor}.
@end multitable

@iftex
@page
@end iftex

@subsection Pillars

@multitable @columnfractions .25 .15 .15 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{PILLAR}
  @tab @center @image{mininim-figures/d-pillar}
  @tab @center @image{mininim-figures/p-pillar}
  @tab

  @item @code{BIG_PILLAR_TOP}
  @tab @center @image{mininim-figures/d-big-pillar-top}
  @tab @center @image{mininim-figures/p-big-pillar-top}
  @tab This should be placed above a @code{BIG_PILLAR_BOTTOM}.  This is
  an @emph{strictly traversable construction}.

  @item @code{BIG_PILLAR_BOTTOM}
  @tab @center @image{mininim-figures/d-big-pillar-bottom}
  @tab @center @image{mininim-figures/p-big-pillar-bottom}
  @tab This should be place below a @code{BIG_PILLAR_TOP}.
@end multitable

@subsection Wall

@multitable @columnfractions .15 .2 .2 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{WALL}
  @tab @center @image{mininim-figures/d-wall}
  @tab @center @image{mininim-figures/p-wall}
  @tab This is a @emph{collidable}, @emph{rigid} and @emph{non-hangable}
  construction.
@end multitable

@iftex
@page
@end iftex

@subsection Doors

@multitable @columnfractions .15 .2 .2 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{DOOR}
  @tab @center @image{mininim-figures/d-door}
  @tab @center @image{mininim-figures/p-door}
  @tab

  @item @code{LEVEL_DOOR}
  @tab @center @image{mininim-figures/d-level-door}
  @tab @center @image{mininim-figures/p-level-door}
  @tab
@end multitable

@subsection Chopper

@multitable @columnfractions .15 .2 .2 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{CHOPPER}
  @tab @center @image{mininim-figures/d-chopper}
  @tab @center @image{mininim-figures/p-chopper}
  @tab

@end multitable

@subsection Mirror

@multitable @columnfractions .15 .2 .2 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{MIRROR}
  @tab @center @image{mininim-figures/d-mirror}
  @tab @center @image{mininim-figures/p-mirror}
  @tab

@end multitable

@iftex
@page
@end iftex

@subsection Carpets

@multitable @columnfractions .15 .2 .2 .45
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{TCARPET}
  @tab @center @image{mininim-figures/d-tcarpet-00}
  @tab @center @image{mininim-figures/p-tcarpet-00}
  @tab

  @item @code{TCARPET}
  @tab @center @image{mininim-figures/d-tcarpet-01}
  @tab @center @image{mininim-figures/p-tcarpet-01}
  @tab

  @item @code{TCARPET}
  @tab @center @image{mininim-figures/d-arch-tcarpet-right-00}
  @tab @center @image{mininim-figures/p-arch-tcarpet-right-00}
  @tab These graphics are drawn for the design
  @code{ARCH_CARPET_RIGHT_00}.  This is designed to end an arch.  This
  should be placed at right of an @code{ARCH_TOP_MID}.

  @item @code{TCARPET}
  @tab @center @image{mininim-figures/d-arch-tcarpet-right-01}
  @tab @center @image{mininim-figures/p-arch-tcarpet-right-01}
  @tab These graphics are drawn for the design
  @code{ARCH_CARPET_RIGHT_01}.  This is designed to end an arch.  This
  should be placed at right of an @code{ARCH_TOP_MID}.

  @item @code{TCARPET}
  @tab @center @image{mininim-figures/d-arch-tcarpet-left}
  @tab @center @image{mininim-figures/p-arch-tcarpet-left}
  @tab These graphics are drawn for the design @code{ARCH_CARPET_LEFT}.
  This is designed to end an arch.  This should be placed two places to
  the left of an @code{ARCH_TOP_MID}.

  @item @code{CARPET}
  @tab @center @image{mininim-figures/d-carpet-00}
  @tab @center @image{mininim-figures/p-carpet-00}
  @tab

  @item @code{CARPET}
  @tab @center @image{mininim-figures/d-carpet-01}
  @tab @center @image{mininim-figures/p-carpet-01}
  @tab

  @item @code{CARPET}
  @tab @center @image{mininim-figures/d-arch-carpet-left}
  @tab @center @image{mininim-figures/p-arch-carpet-left}
  @tab These graphics are drawn for the design @code{ARCH_CARPET_LEFT}.
  This is designed to end an arch.  This should be placed two places to
  the left of an @code{ARCH_TOP_MID}.

@end multitable

@subsection Arches

@multitable @columnfractions .2 .15 .15 .5
  @headitem Code @tab Dungeon
  @footnote{In the original game there is no dungeon version of arches.}
 @tab Palace @tab Notes

  @item @code{ARCH_BOTTOM}
  @tab @center @image{mininim-figures/d-arch-bottom}
  @tab @center @image{mininim-figures/p-arch-bottom}
  @tab This should be placed below an @code{ARCH_TOP_MID}.

  @item @code{ARCH_TOP_MID}
  @tab @center @image{mininim-figures/d-arch-top-mid}
  @tab @center @image{mininim-figures/p-arch-top-mid}
  @tab This should be placed above an @code{ARCH_BOTTOM} and at left of an
  @code{ARCH_TOP_LEFT}, at right of an @code{ARCH_TOP_RIGHT}, or next to
  an @code{ARCH_TOP_SMALL}.

  @item @code{ARCH_TOP_SMALL}
  @tab @center @image{mininim-figures/d-arch-top-small}
  @tab @center @image{mininim-figures/p-arch-top-small}
  @tab This should be placed in between two @code{ARCH_TOP_MID}.

  @item @code{ARCH_TOP_LEFT}
  @tab @center @image{mininim-figures/d-arch-top-left}
  @tab @center @image{mininim-figures/p-arch-top-left}
  @tab This should be placed at left of an @code{ARCH_TOP_RIGHT}.

  @item @code{ARCH_TOP_RIGHT}
  @tab @center @image{mininim-figures/d-arch-top-right}
  @tab @center @image{mininim-figures/p-arch-top-right}
  @tab This should be place at right of an @code{ARCH_TOP_LEFT}.
@end multitable

@section Backgrounds

@multitable @columnfractions .12 .2 .2 .48
  @headitem Code @tab Dungeon @tab Palace @tab Notes

  @item @code{NO_BRICKS}
  @tab
  @tab
  @tab For the dungeon and palace this results in no graphics at all.

  @item @code{NO_BG}
  @tab
  @tab @center @image{mininim-figures/p-bricks-00}
  @tab For the dungeon this results in no graphics at all.  For the palace this
   results in the same graphics as @code{BRICKS_02}.

  @item @code{BRICKS_00}
  @tab @center @image{mininim-figures/d-bricks-00}
  @tab
  @tab For the palace this results in no graphics at all.

  @item @code{BRICKS_01}
  @tab @center @image{mininim-figures/d-bricks-01}
  @tab @center @image{mininim-figures/p-bricks-01}
  @tab For the palace this results in the same graphics as @code{BRICKS_03}

  @item @code{BRICKS_02}
  @tab @center @image{mininim-figures/d-bricks-02}
  @tab @center @image{mininim-figures/p-bricks-00}
  @tab For the palace this results in the same graphics as @code{NO_BG}.

  @item @code{BRICKS_03}
  @tab @center @image{mininim-figures/d-bricks-03}
  @tab @center @image{mininim-figures/p-bricks-01}
  @tab For the palace this results in the same graphics as @code{BRICKS_01}.

  @item @code{TORCH}@footnote{The fire sprites are mirrored
  horizontally depending on the level coordinates the torch has.
  This is not so in the original game.}
  @tab @center @image{mininim-figures/d-torch}
  @tab @center @image{mininim-figures/p-torch}
  @tab

  @item @code{WINDOW}
  @tab @center @image{mininim-figures/d-window}
  @tab @center @image{mininim-figures/p-window}
  @tab

  @item @code{BALCONY}@footnote{The background stars are randomly
  positioned and animated.  In the original game, all balconies have
  non-animated white stars in fixed positions.}
  @tab @center @image{mininim-figures/d-balcony}
  @tab @center @image{mininim-figures/p-balcony}
@end multitable



@c --- Movements;
@node Movements
@chapter Movements
@cindex movements

In his journey to save the princess, the kid has to endure several
levels full of challenging traps and skilled opponents.  Run, walk,
turn, crouch, jump, hang, climb, take sword, attack, defend are some of
the kid's movements at your disposal to help him make his way to the
princess tower.  Although, this is a relatively large set of movements,
basically all these movements are accomplished by some combination of
the directional and shift keys, often conditioned to the current kid's
movement state.  This chapter explains in detail all possible movements
of the kid.

There are four major modes of movement: @dfn{normal}, @dfn{crouch},
@dfn{run} and @dfn{fight}.  The major mode the kid is in is the foremost
element determining how the input is translated into kid's movements.

@heading Normal

The major movement mode at the beginning of each level is normal.  While
in it the kid stands at rest.

@center @image{mininim-figures/kid-normal-right}

If you press the horizontal directional key in the opposite direction
the kid is facing, he @strong{turns} and then faces the opposite
direction likewise.

@center @image{mininim-figures/kid-normal-right} @arrow{} @image{mininim-figures/kid-turn} @arrow{} @image{mininim-figures/kid-normal-left}

Pressing the up directional key, makes the kid perform a
@strong{vertical jump}.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-vjump}

Pressing the up and the horizontal directional keys at once makes the
kid @strong{jump} forward.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-jump}

Pressing the horizontal directional key in the same direction the kid is
facing while holding the shift key, makes him @strong{walk} carefully.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-walk}


@heading Crouch

If you press the down directional the kid crouches.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-couch}

The kid stays crouched as long as you keep the down directional pressed.
If you press the horizontal directional key in the same direction the
kid is facing, without releasing the down directional, the kid performs
little @strong{crouching jumps} forwards.

@center @image{mininim-figures/kid-couch} @arrow{} @image{mininim-figures/kid-couch-forward} @arrow{} @image{mininim-figures/kid-couch}

Releasing the down directional makes the kid stand up again.

@center @image{mininim-figures/kid-uncouch} @arrow{} @image{mininim-figures/kid-normal-left}


@heading Run

Pressing the horizontal directional key in the same direction the kid is
facing, makes him start to run.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-start-run}

He runs as long as you keep the directional key pressed.

@center @image{mininim-figures/kid-start-run} @arrow{} @image{mininim-figures/kid-run}

In case you press the up directional key while running, he makes a
@strong{running jump}, and continue to run if you keep the horizontal
directional pressed.

@center @image{mininim-figures/kid-run} @arrow{} @image{mininim-figures/kid-run-jump}

Instead, if you press the down directional key, he @strong{crouches}
slipping with some inertia, and then the crouching input rules apply.

@center @image{mininim-figures/kid-run} @arrow{} @image{mininim-figures/kid-couch}

If you press the horizontal directional key in the opposite direction
the kid is facing while running, he @strong{turns} without stopping.

@center @image{mininim-figures/kid-run} @arrow{} @image{mininim-figures/kid-turn-run}

He continues to run while you keep the directional pressed, but
releasing the directional key makes him stop, and go back to the normal
stage.

@center @image{mininim-figures/kid-stop-run} @arrow{} @image{mininim-figures/kid-normal-left}


@heading Fight

If the kid has got the sword, the return key @strong{takes the sword}
and puts him in fight mode.

@center @image{mininim-figures/kid-normal-left} @arrow{} @image{mininim-figures/kid-take-sword} @arrow{} @image{mininim-figures/kid-sword-normal}

Pressing the horizontal directional key in the same direction kid is
facing, makes him @strong{walk forward}.

@center @image{mininim-figures/kid-sword-normal} @arrow{} @image{mininim-figures/kid-sword-walkf}

Likewise if you press in the opposite direction, he @strong{goes
backward}.

@center @image{mininim-figures/kid-sword-normal} @arrow{} @image{mininim-figures/kid-sword-walkb}

If you press the up directional, the kid makes the @strong{defense
movement}.

@center @image{mininim-figures/kid-sword-normal} @arrow{} @image{mininim-figures/kid-sword-defense}

The shift key make him @strong{attack}.

@center @image{mininim-figures/kid-sword-normal} @arrow{} @image{mininim-figures/kid-sword-attack}

Finally you can make him @strong{keep the sword} and return to normal
mode by pressing the down directional.

@center @image{mininim-figures/kid-sword-normal} @arrow{} @image{mininim-figures/kid-keep-sword} @arrow{} @image{mininim-figures/kid-normal-left}


@c 
@c @c --- Preface;
@c @node Preface
@c @unnumbered Preface
@c @cindex introduction

@c <Here comes an introduction to MININIM and its documentation>



@c 
@c @c --- Overview;
@c @node Overview
@c @chapter Overview
@c @include README.texi




@c 
@c @c --- Release;
@c @node Release
@c @chapter Release

@c In this chapter one can find information that are specific to the
@c current release or subject to change between releases.  It
@c presents the features this package acquired over time, problems that
@c affect its overall usage and what possibly could happen to it --- by
@c our wishes --- in the future.  Last but not least, people whose
@c contribution for this package are noteworthy are acknowledged.

@c @menu
@c Present and Future:
@c * Announcement::  Published announcement message of this new release;
@c * News::          User-visible changes since previous versions;
@c * To do::         Features we want to see implemented someday;

@c People:
@c * Authors::  List of major contributors;
@c * Thanks::   List of minor contributors;
@c * Donors::   People who supported the development by donations;
@c @end menu




@c 
@c @c --- News;
@c @page
@c @node Announcement
@c @section Announcement
@c @include ANNOUNCEMENT.texi




@c 
@c @c --- News;
@c @page
@c @node News
@c @section News
@c @include NEWS.texi




@c 
@c @c --- To do;
@c @page
@c @node To do
@c @section To do
@c @include TODO.texi




@c 
@c @c --- Authors;
@c @page
@c @node Authors
@c @section Authors
@c @include AUTHORS.texi




@c 
@c @c --- Thanks;
@c @page
@c @node Thanks
@c @section Thanks
@c @include THANKS.texi




@c 
@c @c --- Donors;
@c @page
@c @node Donors
@c @section Donors
@c @include DONORS.texi




@c 
@c @c --- GNU Free Documentation License;
@c @node GNU Free Documentation License
@c @appendix GNU Free Documentation License
@c @cindex license documentation
@c @cindex documentation license
@c @cindex license of manual
@c @cindex manual license
@c @cindex copying documentation
@c @cindex documentation copying
@c @cindex copying manual
@c @cindex manual copying

@c @include gnu-free-documentation-license.texi




@c 
@c @c --- The GNU Manifesto;
@c @node The GNU Manifesto
@c @appendix The GNU Manifesto
@c @include the-gnu-manifesto.texi




@c 
@c @c --- The GNU Project;
@c @node The GNU Project
@c @appendix The GNU Project
@c @include the-gnu-project.texi




@c 
@c @c --- Linux and the GNU system;
@c @node Linux and the GNU system
@c @appendix Linux and the GNU system
@c @include linux-and-the-gnu-system.texi




@c 
@c @c --- Why Software Should Not Have Owners;
@c @node Why Software Should Not Have Owners
@c @appendix Why Software Should Not Have Owners
@c @include why-software-should-not-have-owners.texi




@c 
@c @c --- Why Free Software Needs Free Documentation;
@c @node Why Free Software Needs Free Documentation
@c @appendix Why Free Software Needs Free Documentation
@c @include why-free-software-needs-free-documentation.texi





@c --- Index;
@node Index
@unnumbered Index

@printindex cp

@bye
