#!/bin/bash
prefix=spikes
d=1
for i in {1..5}
do find -name '*.c' -or -name '*.h' |
   xargs sed -i "s/${prefix}_$(printf "%02d" $i)/${prefix}_$(printf "%02d" $(($i - $d)))/g;s/${prefix^^}_$(printf "%02d" $i)/${prefix^^}_$(printf "%02d" $(($i - $d)))/g"
done
